# Generated by Django 2.1.8 on 2019-07-17 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190717_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerindex',
            name='QC_Date',
        ),
        migrations.RemoveField(
            model_name='registerindex',
            name='QC_Date_review',
        ),
        migrations.RemoveField(
            model_name='ruleslist',
            name='qc_rule',
        ),
        migrations.RemoveField(
            model_name='ruleslist',
            name='qc_rule_review',
        ),
    ]
