# Generated by Django 2.1.10 on 2019-07-24 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190717_1222'),
        ('api', '0003_auto_20190717_1436'),
    ]

    operations = [
    ]
