# Generated by Django 2.1.7 on 2019-07-25 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190717_1436'),
        ('api', '0004_auto_20190717_1222'),
    ]

    operations = [
    ]
