app_id: 7ac7fd80-fe16-4120-8aa7-dc4b72d25d92
app_secret: nkIhqNA=q8P9*bunwnUw]dYEFB7nNz.6
redirect: http://localhost:8000/weightcalculation/callback
scopes: openid profile offline_access user.read calendars.read
authority: https://login.microsoftonline.com/common
authorize_endpoint: /oauth2/v2.0/authorize
token_endpoint: /oauth2/v2.0/token
